
version: '3.8'

services:
  stan:
    image: nats-streaming:latest
    container_name: stan
    ports:
      - "4222:4222"  # NATS client
      - "8222:8222"  # HTTP monitoring
    volumes:
      - nats-data:/data
      - ./stan-server.conf:/etc/stan/stan-server.conf  # Примонтирование конфигурационного файла
    command: [
      "-m", "8222",        # включение HTTP мониторинга на порту 8222
      "-p", "4222",        # основной порт для NATS соединений
      "-sc", "/etc/stan/stan-server.conf",
    ]

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres-data:
  redis-data:
  nats-data:
