version: '3.8'

services:
  stan:
    image: nats-streaming:latest
    container_name: stan
    ports:
      - "4222:4222"  # NATS client
      - "8222:8222"  # HTTP monitoring
      - "8223:8223"  # HTTPS monitoring
    environment:
      - CLUSTER_ID=test-cluster  # Set the cluster ID
      - NATS_URL=nats://0.0.0.0:4222  # NATS URL

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres-data:
  redis-data:
